## numpy examples

In [19]:
import numpy as np
A = [[1, 0], [0, 1]]
B = [[4, 1], [2, 2]]
A = np.array(A)
B = np.array(B)
np.dot(A, B)

array([[4, 1],
       [2, 2]])

In [42]:
Binv = np.linalg.inv(B)
print(Binv)
np.dot(B,Binv)

[[ 0.33333333 -0.16666667]
 [-0.33333333  0.66666667]]


array([[1., 0.],
       [0., 1.]])

In [9]:
B.sum(axis=0)

array([6, 3])

In [10]:
B.sum(axis=1)

array([5, 4])

In [14]:
A = np.array([[2, 3, 4], [5, 6, 7]])
B = np.ones([3,3])

In [15]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.dot(B,A)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [17]:
2 ** A

array([[  4,   8,  16],
       [ 32,  64, 128]])

In [18]:
3 + A

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [44]:
A = np.array([[3, 4, 5],[6,7,8],[9,10,11]])

array([[  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

## Regression example

In [13]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# Load the diabetes dataset
diabetes = datasets.load_diabetes()

# Use only one feature
#diabetes_X = diabetes.data[:, np.newaxis, 2]

diabetes_X = diabetes.data

# Split the data into training/testing sets
diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]

# Split the targets into training/testing sets
diabetes_y_train = diabetes.target[:-20]
diabetes_y_test = diabetes.target[-20:]

# Create linear regression object
#regr = linear_model.Ridge(alpha=0)
regr = linear_model.Ridge(alpha=10)

# Train the model using the training sets
regr.fit(diabetes_X_train, diabetes_y_train)

# Make predictions using the testing set
diabetes_y_pred = regr.predict(diabetes_X_test)

# The coefficients
print('Coefficients: \n', regr.coef_)
print('Intercept: \n', regr.intercept_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(diabetes_y_test, diabetes_y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(diabetes_y_test, diabetes_y_pred))

# Plot outputs
#plt.scatter(diabetes_X_test, diabetes_y_test,  color='black')
#plt.plot(diabetes_X_test, diabetes_y_pred, color='blue', linewidth=3)

#plt.show()

Coefficients: 
 [ 19.8042417   -1.23141146  71.81409161  52.85333292  19.89794183
  14.13225275 -45.26141301  47.34057094  67.39758219  43.43459791]
Intercept: 
 153.30386725032426
Mean squared error: 4436.63
Variance score: 0.08


## Ridge regression

In [10]:
from sklearn import linear_model
reg = linear_model.Ridge(alpha=10)
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1]) 
print(reg.coef_)
print(reg.intercept_)

[0.05588235 0.05588235]
0.3294117647058824


In [11]:
from sklearn import linear_model
reg = linear_model.Ridge(alpha=.01)
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1]) 
print(reg.coef_)
print(reg.intercept_)

[0.47146402 0.47146402]
0.052357320099255644
